version: '3.4'

services:
  xiaperls:
    image: xiaperls
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
         - NODE_BUILD_ENV=production
    env_file:
      - ./.env
    command: ["npm", "start"]
    volumes:
      - C:/Users/kjijo/Documents/dockerRun/cacert.pem:/etc/ssl/certs/ca-certificates.pem
    networks:
      - openlxp

networks:
  openlxp:
    external: true

